version: '2'
services:
  db:
    image: mysql:5.6
    restart: always
    env_file:
      - ./.docker.env
    ports:
      - "3307:3306"
    volumes:
      - "./mysql-data:/var/lib/mysql"

  web:
    build:
      context: ../
      dockerfile: _docker/Dockerfile
    env_file:
      - ./.docker.env
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - ./../web:/var/www/site
    links:
      - db
    environment:
      C5_ENVIRONMENT: dev
      MYSQL_HOST: db
